/* Core */
import { createSlice, type PayloadAction } from "@reduxjs/toolkit";
import { getRecentYears, months } from "@/app/utils";


/* Instruments */
import { incrementAsync } from "./thunks";

const initialState: CounterSliceState = {
  value: 0,
  status: "idle",
  years: getRecentYears(),
  months,
};

export const incomeSlice = createSlice({
  name: "income",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    
    increment: (state) => {
      state.value += 1;
    },
    decrement: (state) => {
      state.value -= 1;
    },
    incrementByAmount: (state, action: PayloadAction<number>) => {
      state.value += action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(incrementAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(incrementAsync.fulfilled, (state, action) => {
        state.status = "idle";
        state.value += action.payload;
      });
  },
});

/* Types */
export interface CounterSliceState {
  value: number;
  status: "idle" | "loading" | "failed";
  years: Options;
  months: Options;
}